AllCops:
  TargetRubyVersion: 2.5
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/SafeNavigation:
  Enabled: false
